// <auto-generated />
namespace HospitalModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class deletedDiagnosis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletedDiagnosis));
        
        string IMigrationMetadata.Id
        {
            get { return "202001160516253_deletedDiagnosis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
